import Head from 'next/head'
import Image from 'next/image'
import {useState} from 'react';
import {Product, TitleCard} from '../components'
import {IProduct} from '../components/Product/Product.types';

interface HomeProps {
    data: IProduct[]
}

export default function Home({data}: HomeProps) {

    const [basket, setBasket] = useState<IProduct[]>([]);
    const [favorite, setFavorite] = useState<IProduct[]>([]);


    function handleBasket(product: IProduct) {
        const isInBasket = basket.includes(product);
        isInBasket ? setBasket((v) => v.filter((item) => item.id !== product.id)) : setBasket((v) => [...v, product]);
    }

    function handleFavorites(product: IProduct) {
        const isFavorite = favorite.includes(product);
        isFavorite ? setFavorite((v) => v.filter((item) => item.id !== product.id)) : setFavorite((v) => [...v, product]);
    }

    const items = data ?? [];

    return (
        <>
            <Head>
                <title>Azalia test task</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="main">
                <TitleCard />
                {items.map((product) =>
                    <Product
                        key={product.id}
                        product={product}
                        isInBasket={basket.includes(product)}
                        isFavorite={favorite.includes(product)}
                        addToBasket={() => handleBasket(product)}
                        addToFavorites={() => handleFavorites(product)}
                    />
                )}
            </main>
        </>
    )
}


export async function getServerSideProps() {
    const res = await fetch('https://fakestoreapi.com/products')
    const data = await res.json()
    return {props: {data}}
}